repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: mixed-line-ending
        args: ['--fix=lf']
      - id: no-commit-to-branch
        args: [--branch, master, --branch, prod]
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: check-yaml
      - id: check-json
      - id: detect-aws-credentials
      - id: detect-private-key
