{
 "title": "GG 7 Days To Die - Rebirth",
 "time": { "from": "2026-02-28T23:00:00.000Z", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gg_player_list",
    "query": "Dude|haas2|Lost|Galiwyr|Bright|WhichWitch"
   },
   { "name": "rebirth_run", "label": "Rebirth Run", "query": "1,2" }
  ]
 },
 "panels": [
  {
   "title": "Current Day",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "last_over_time(\r\n    {rebirth_run=\"1\"} |= \"INFO Detected day\"\r\n    | regexp `INFO Detected day (?P<currentday>\\d+),`\r\n    | unwrap currentday\r\n    [$__range]\r\n)"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "last_over_time(\r\n    {rebirth_run=\"1\"} |= \"BloodMoon SetDay\"\r\n    | regexp `BloodMoon SetDay: day (?P<ingameday>\\d+),`\r\n    | unwrap ingameday\r\n    [$__range]\r\n)"
    }
   ]
  },
  {
   "title": "Days until Bloodmoon",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "days" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "max(\r\n    last_over_time (\r\n        {rebirth_run=\"1\"} |= \"INFO Detected day\"\r\n        | regexp `INFO Detected day (?P<currentday>\\d+),`\r\n        | label_format metric=\"currentday\"\r\n        | unwrap currentday\r\n        [$__range]\r\n    )\r\n) by (metric)",
     "legendFormat": "currentday"
    },
    {
     "direction": "backward",
     "expr": "max(\r\n    last_over_time (\r\n        {job=\"7d2d\",rebirth_run=\"1\"} |= \"INF BloodMoon SetDay\"\r\n        | regexp `INF BloodMoon SetDay: day (?P<currentday>\\d+), last day (?P<lastday>\\d+), freq (?P<freq>\\d+), range`\r\n        | label_format metric=\"freq\"\r\n        | unwrap freq\r\n        [$__range]\r\n    )\r\n) by (metric)",
     "legendFormat": "{{freq}}"
    },
    {
     "direction": "backward",
     "expr": "max(\r\n    last_over_time (\r\n        {job=\"7d2d\",rebirth_run=\"1\"} |= \"INF BloodMoon SetDay\"\r\n        | regexp `INF BloodMoon SetDay: day (?P<currentday>\\d+), last day (?P<lastday>\\d+), freq (?P<freq>\\d+), range`\r\n        | label_format metric=\"lastday\"\r\n        | unwrap lastday\r\n        [$__range]\r\n    )\r\n) by (metric)"
    }
   ]
  },
  {
   "title": "Bloodmoons passed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\r\n    {job=\"7d2d\",rebirth_run=\"1\"} |= \"BloodMoon starting for day\"\r\n    [$__range]\r\n  )"
    }
   ]
  },
  {
   "title": "Time Resets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count_over_time(\r\n    {rebirth_run=\"1\"} |= \"resetting day\"\r\n    [$__range]\r\n)"
    }
   ]
  },
  {
   "title": "Current Game Stage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "last_over_time(\r\n  {job=\"7d2d\",rebirth_run=\"1\"} |= \"gameStage\"\r\n  | regexp `Player id (?P<playerID>\\d+), gameStage (?P<GameStage>\\d+)`\r\n  | label_format playerID=\"{{.playerID}}\"\r\n  | unwrap GameStage\r\n  [$__range]\r\n) by (playerID)"
    }
   ]
  },
  {
   "title": "Leaderboard",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(player)(\r\n  count_over_time(\r\n    {job=\"7d2d\",rebirth_run=\"1\"} |= \"joined the game\"\r\n    | regexp `Player '(?P<player>[^']+)' joined`\r\n    [$__range]\r\n  )\r\n)"
    },
    {
     "direction": "backward",
     "expr": "  sum by(player)(\r\n    sum_over_time(\r\n        {job=\"7d2d\",rebirth_run=\"1\"} |= \"disconnected after\"\r\n        | regexp `Player (?P<player>\\S+) disconnected after (?P<minutes>[0-9.]+) minutes`\r\n        | unwrap minutes\r\n        [$__range]\r\n    )\r\n  )"
    },
    {
     "direction": "backward",
     "expr": "sum by(player)(\r\n  count_over_time(\r\n    {job=\"7d2d\",rebirth_run=\"1\"} |= \"died\"\r\n    | regexp `Player '(?P<player>[^']+)' died`\r\n    | player != \"\"\r\n    [$__range]\r\n  )\r\n)"
    },
    {
     "direction": "backward",
     "expr": "sum by(player)(\r\n  count_over_time(\r\n    {job=\"7d2d\",rebirth_run=\"1\"} |= \"killed by\"\r\n    | regexp `Entity (?P<victim>.+) (?P<victimID>\\d+) killed by (?P<player>.+) (?P<playerID>\\d+)`\r\n    | player=~\"^(Dude|haas2|Lost|Galiwyr|Bright|WhichWitch)$\" \r\n    [$__range]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Total time online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sort_desc(\r\n  sum by(player)(\r\n    sum_over_time(\r\n        {job=\"7d2d\",rebirth_run=\"1\"} |= \"disconnected after\"\r\n        | regexp `Player (?P<player>\\S+) disconnected after (?P<minutes>[0-9.]+) minutes`\r\n        | unwrap minutes\r\n        [$__range]\r\n    )\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Victim heatmap",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kills" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "  count_over_time(\r\n    {job=\"7d2d\",rebirth_run=\"1\"} |= \"killed by\"\r\n    | regexp `Entity (?P<victim>.+) (?P<victimID>\\d+) killed by (?P<killer>.+) (?P<killerID>\\d+)`\r\n    | killer=~\"^(Dude|haas2|Lost|Galiwyr|Bright|WhichWitch)$\" | keep victim,killer\r\n    [$__range]\r\n  )"
    }
   ]
  },
  {
   "title": "Kills by any player, dog or zombie",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(player)(\r\n  count_over_time(\r\n    {job=\"7d2d\",rebirth_run=\"1\"} |= \"killed by\"\r\n    | regexp `Entity (?P<victim>.+) (?P<victimID>\\d+) killed by (?P<player>.+) (?P<playerID>\\d+)`\r\n    [$__range]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Death Race",
   "type": "timeseries",
   "gridPos": { "h": 19, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "deaths" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(player)(\r\n  count_over_time(\r\n    {job=\"7d2d\",rebirth_run=\"1\"} |= \"died\" \r\n    | regexp `Player '(?P<player>[^']+)' died`\r\n    | player != \"\"\r\n    [$__range]\r\n  )\r\n)",
     "legendFormat": "{{player}}"
    }
   ]
  },
  {
   "title": "GameStage per Player",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "max by(playerid) (\r\n  last_over_time(\r\n    {job=\"7d2d\",rebirth_run=\"1\"} |= \"gameStage\"\r\n    | regexp `Player id (?P<playerid>\\d+), gameStage (?P<gamestage>\\d+)`\r\n    | unwrap gamestage\r\n    [$__interval]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Server Stuff",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of objects",
     "type": "timeseries",
     "description": "max per day",
     "gridPos": { "h": 12, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "direction": "backward",
       "expr": "  max_over_time(\r\n  {job=\"7d2d\",rebirth_run=\"1\"} |~ \"INF Time: .*\"\r\n  | regexp `Ply: (?P<Ply>\\d+) Zom: \\d+ Ent: \\d+ `\r\n  | label_format metric=\"Ply\"\r\n  | unwrap Ply\r\n  [$__interval]\r\n) by (metric)\r\n"
      },
      {
       "direction": "backward",
       "expr": "max_over_time(\r\n    {job=\"7d2d\",rebirth_run=\"1\"} |~ \"INF Time: .*\"\r\n    | regexp `Ply: \\d+ Zom: (?P<Zom>\\d+) Ent: \\d+ `\r\n    | label_format metric=\"Zom\"\r\n    | unwrap Zom\r\n    [$__interval]\r\n) by (metric)"
      },
      {
       "direction": "backward",
       "expr": "max_over_time(\r\n    {job=\"7d2d\",rebirth_run=\"1\"} |~ \"INF Time: .*\"\r\n    | regexp `Ply: \\d+ Zom: \\d+ Ent: (?P<Ent>\\d+) `\r\n    | label_format metric=\"Ent\"\r\n    | unwrap Ent\r\n    [$__interval]\r\n) by (metric)"
      },
      {
       "direction": "backward",
       "expr": "max_over_time(\r\n    {job=\"7d2d\",rebirth_run=\"1\"} |~ \"INF Time: .*\"\r\n    | regexp ` CO: (?P<CO>\\d+) `\r\n    | label_format metric=\"CO\"\r\n    | unwrap CO\r\n    [$__interval]\r\n) by (metric)"
      }
     ]
    },
    {
     "title": "Memory usage",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "direction": "backward",
       "expr": "  max_over_time(\r\n  {job=\"7d2d\",rebirth_run=\"1\"} |~ \"INF Time: .*\"\r\n  | regexp `Heap: (?P<heap>[\\d\\.]+)MB`\r\n  | label_format metric=\"heap\"\r\n  | unwrap heap\r\n  [$__interval]\r\n) by (metric)\r\n"
      },
      {
       "direction": "backward",
       "expr": "  max_over_time(\r\n  {job=\"7d2d\",rebirth_run=\"1\"} |~ \"INF Time: .*\"\r\n  | regexp `Max: (?P<max>[\\d\\.]+)MB`\r\n  | label_format metric=\"Max\"\r\n  | unwrap max\r\n  [$__interval]\r\n) by (metric)"
      },
      {
       "direction": "backward",
       "expr": "  max_over_time(\r\n  {job=\"7d2d\",rebirth_run=\"1\"} |~ \"INF Time: .*\"\r\n  | regexp `RSS: (?P<rss>[\\d\\.]+)MB`\r\n  | label_format metric=\"RSS\"\r\n  | unwrap rss\r\n  [$__interval]\r\n) by (metric)"
      },
      {
       "direction": "backward",
       "expr": "  max_over_time(\r\n  {job=\"7d2d\",rebirth_run=\"1\"} |~ \"INF Time: .*\"\r\n  | regexp `Chunks: (?P<Chunks>[\\d\\.]+) `\r\n  | label_format metric=\"Chunks\"\r\n  | unwrap Chunks\r\n  [$__interval]\r\n) by (metric)"
      }
     ]
    },
    {
     "title": "GameTime since last server restart",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "m" } },
     "targets": [
      {
       "direction": "backward",
       "expr": "  max_over_time(\r\n  {job=\"7d2d\",rebirth_run=\"1\"} |~ \"INF Time: .*\"\r\n  | regexp `INF Time: (?P<gametime>\\d+\\.\\d\\d)m `\r\n  | label_format metric=\"gametime\"\r\n  | unwrap gametime\r\n  [$__interval]\r\n) by (metric)"
      }
     ]
    }
   ]
  }
 ]
}